
services:
  # Apache Solr Search Engine
  solr:
    image: docker.io/library/solr:9.4
    container_name: pokemon-solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./solr/configsets:/opt/solr/server/solr/configsets
    environment:
      - SOLR_HEAP=512m
    command: >
      bash -c "
        solr-precreate pokemon /opt/solr/server/solr/configsets/_default && 
        solr-foreground
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - pokemon-network

  # Web Frontend for Search
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: pokemon-web
    ports:
      - "5000:5000"
    environment:
      - SOLR_URL=http://solr:8983/solr/pokemon
      - FLASK_ENV=development
    depends_on:
      solr:
        condition: service_healthy
    volumes:
      - ./web:/app
    networks:
      - pokemon-network

  # Optional: Solr Admin UI (already included in solr service)
  # You can access it at http://localhost:8983/solr

volumes:
  solr_data:
    driver: local

networks:
  pokemon-network:
    driver: bridge